[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api-gateway/Dockerfile.production"
buildContext = "."

[deploy]
startCommand = "node dist/ultra-minimal-index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10