[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api-gateway/Dockerfile"
buildContext = "."

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10