[build]
builder = "DOCKERFILE"
dockerfilePath = "apps/api-gateway/Dockerfile.production"
buildContext = "."

[deploy]
startCommand = "node src/standalone-auth.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10