// Supabase generated types will go here
// This file will be auto-generated by: supabase gen types typescript --local

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string
          name: string
          org_number: string | null
          email: string
          phone: string | null
          address: Json | null
          stripe_account_id: string | null
          stripe_onboarding_complete: boolean
          reward_settings: Json
          status: string
          trial_feedbacks_remaining: number
          trial_expires_at: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          org_number?: string | null
          email: string
          phone?: string | null
          address?: Json | null
          stripe_account_id?: string | null
          stripe_onboarding_complete?: boolean
          reward_settings?: Json
          status?: string
          trial_feedbacks_remaining?: number
          trial_expires_at?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          org_number?: string | null
          email?: string
          phone?: string | null
          address?: Json | null
          stripe_account_id?: string | null
          stripe_onboarding_complete?: boolean
          reward_settings?: Json
          status?: string
          trial_feedbacks_remaining?: number
          trial_expires_at?: string
          created_at?: string
          updated_at?: string
        }
      }
      business_locations: {
        Row: {
          id: string
          business_id: string
          name: string
          address: string | null
          pos_location_id: string | null
          qr_code_url: string | null
          qr_code_expires_at: string
          active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          address?: string | null
          pos_location_id?: string | null
          qr_code_url?: string | null
          qr_code_expires_at?: string
          active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          name?: string
          address?: string | null
          pos_location_id?: string | null
          qr_code_url?: string | null
          qr_code_expires_at?: string
          active?: boolean
          created_at?: string
        }
      }
      feedback_sessions: {
        Row: {
          id: string
          business_id: string
          location_id: string | null
          customer_hash: string
          device_fingerprint: Json | null
          qr_token: string
          qr_scanned_at: string
          transaction_id: string | null
          transaction_amount: number | null
          transaction_items: Json | null
          transaction_matched_at: string | null
          audio_duration_seconds: number | null
          audio_url: string | null
          transcript: string | null
          transcript_language: string
          ai_evaluation: Json | null
          quality_score: number | null
          authenticity_score: number | null
          concreteness_score: number | null
          depth_score: number | null
          sentiment_score: number | null
          feedback_categories: string[] | null
          fraud_risk_score: number | null
          fraud_flags: Json | null
          fraud_review_status: string
          reward_tier: string | null
          reward_amount: number | null
          reward_percentage: number | null
          reward_processed_at: string | null
          stripe_transfer_id: string | null
          status: string
          error_message: string | null
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          location_id?: string | null
          customer_hash: string
          device_fingerprint?: Json | null
          qr_token: string
          qr_scanned_at?: string
          transaction_id?: string | null
          transaction_amount?: number | null
          transaction_items?: Json | null
          transaction_matched_at?: string | null
          audio_duration_seconds?: number | null
          audio_url?: string | null
          transcript?: string | null
          transcript_language?: string
          ai_evaluation?: Json | null
          quality_score?: number | null
          authenticity_score?: number | null
          concreteness_score?: number | null
          depth_score?: number | null
          sentiment_score?: number | null
          feedback_categories?: string[] | null
          fraud_risk_score?: number | null
          fraud_flags?: Json | null
          fraud_review_status?: string
          reward_tier?: string | null
          reward_amount?: number | null
          reward_percentage?: number | null
          reward_processed_at?: string | null
          stripe_transfer_id?: string | null
          status?: string
          error_message?: string | null
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          location_id?: string | null
          customer_hash?: string
          device_fingerprint?: Json | null
          qr_token?: string
          qr_scanned_at?: string
          transaction_id?: string | null
          transaction_amount?: number | null
          transaction_items?: Json | null
          transaction_matched_at?: string | null
          audio_duration_seconds?: number | null
          audio_url?: string | null
          transcript?: string | null
          transcript_language?: string
          ai_evaluation?: Json | null
          quality_score?: number | null
          authenticity_score?: number | null
          concreteness_score?: number | null
          depth_score?: number | null
          sentiment_score?: number | null
          feedback_categories?: string[] | null
          fraud_risk_score?: number | null
          fraud_flags?: Json | null
          fraud_review_status?: string
          reward_tier?: string | null
          reward_amount?: number | null
          reward_percentage?: number | null
          reward_processed_at?: string | null
          stripe_transfer_id?: string | null
          status?: string
          error_message?: string | null
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      pos_connections: {
        Row: {
          id: string
          business_id: string
          provider: string
          provider_account_id: string
          credentials: Json | null
          webhook_endpoint_id: string | null
          webhook_secret: string | null
          last_sync_at: string | null
          sync_status: string
          error_message: string | null
          active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          provider: string
          provider_account_id: string
          credentials?: Json | null
          webhook_endpoint_id?: string | null
          webhook_secret?: string | null
          last_sync_at?: string | null
          sync_status?: string
          error_message?: string | null
          active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          provider?: string
          provider_account_id?: string
          credentials?: Json | null
          webhook_endpoint_id?: string | null
          webhook_secret?: string | null
          last_sync_at?: string | null
          sync_status?: string
          error_message?: string | null
          active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      consent_records: {
        Row: {
          id: string
          session_id: string | null
          customer_hash: string
          consent_type: string
          granted: boolean
          ip_address: string | null
          user_agent: string | null
          consent_version: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          session_id?: string | null
          customer_hash: string
          consent_type: string
          granted: boolean
          ip_address?: string | null
          user_agent?: string | null
          consent_version?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          session_id?: string | null
          customer_hash?: string
          consent_type?: string
          granted?: boolean
          ip_address?: string | null
          user_agent?: string | null
          consent_version?: string
          created_at?: string
          updated_at?: string
        }
      }
      data_requests: {
        Row: {
          id: string
          customer_hash: string
          request_type: string
          status: string
          requested_at: string
          completed_at: string | null
          download_url: string | null
          download_token: string | null
          expires_at: string | null
          data_size_bytes: number | null
          error_message: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          customer_hash: string
          request_type: string
          status?: string
          requested_at?: string
          completed_at?: string | null
          download_url?: string | null
          download_token?: string | null
          expires_at?: string | null
          data_size_bytes?: number | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          customer_hash?: string
          request_type?: string
          status?: string
          requested_at?: string
          completed_at?: string | null
          download_url?: string | null
          download_token?: string | null
          expires_at?: string | null
          data_size_bytes?: number | null
          error_message?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      data_retention_log: {
        Row: {
          id: string
          data_category: string
          retention_policy: string
          records_processed: number
          records_deleted: number
          records_anonymized: number
          cutoff_date: string
          execution_started_at: string
          execution_completed_at: string | null
          execution_duration_seconds: number | null
          status: string
          error_message: string | null
          created_at: string
        }
        Insert: {
          id?: string
          data_category: string
          retention_policy: string
          records_processed?: number
          records_deleted?: number
          records_anonymized?: number
          cutoff_date: string
          execution_started_at: string
          execution_completed_at?: string | null
          execution_duration_seconds?: number | null
          status?: string
          error_message?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          data_category?: string
          retention_policy?: string
          records_processed?: number
          records_deleted?: number
          records_anonymized?: number
          cutoff_date?: string
          execution_started_at?: string
          execution_completed_at?: string | null
          execution_duration_seconds?: number | null
          status?: string
          error_message?: string | null
          created_at?: string
        }
      }
      voice_data_tracking: {
        Row: {
          id: string
          session_id: string
          customer_hash: string
          audio_file_path: string | null
          audio_size_bytes: number | null
          processing_started_at: string
          processing_completed_at: string | null
          deletion_scheduled_at: string | null
          deleted_at: string | null
          status: string
          error_message: string | null
        }
        Insert: {
          id?: string
          session_id: string
          customer_hash: string
          audio_file_path?: string | null
          audio_size_bytes?: number | null
          processing_started_at?: string
          processing_completed_at?: string | null
          deletion_scheduled_at?: string | null
          deleted_at?: string | null
          status?: string
          error_message?: string | null
        }
        Update: {
          id?: string
          session_id?: string
          customer_hash?: string
          audio_file_path?: string | null
          audio_size_bytes?: number | null
          processing_started_at?: string
          processing_completed_at?: string | null
          deletion_scheduled_at?: string | null
          deleted_at?: string | null
          status?: string
          error_message?: string | null
        }
      }
      gdpr_audit_log: {
        Row: {
          id: string
          customer_hash: string | null
          action_type: string
          action_details: Json | null
          admin_id: string | null
          ip_address: string | null
          user_agent: string | null
          legal_basis: string | null
          created_at: string
        }
        Insert: {
          id?: string
          customer_hash?: string | null
          action_type: string
          action_details?: Json | null
          admin_id?: string | null
          ip_address?: string | null
          user_agent?: string | null
          legal_basis?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          customer_hash?: string | null
          action_type?: string
          action_details?: Json | null
          admin_id?: string | null
          ip_address?: string | null
          user_agent?: string | null
          legal_basis?: string | null
          created_at?: string
        }
      }
      pii_detection_log: {
        Row: {
          id: string
          source_table: string
          source_id: string
          source_field: string
          pii_types: string[] | null
          anonymization_method: string | null
          confidence_score: number | null
          detected_at: string
          anonymized_at: string | null
          status: string
        }
        Insert: {
          id?: string
          source_table: string
          source_id: string
          source_field: string
          pii_types?: string[] | null
          anonymization_method?: string | null
          confidence_score?: number | null
          detected_at?: string
          anonymized_at?: string | null
          status?: string
        }
        Update: {
          id?: string
          source_table?: string
          source_id?: string
          source_field?: string
          pii_types?: string[] | null
          anonymization_method?: string | null
          confidence_score?: number | null
          detected_at?: string
          anonymized_at?: string | null
          status?: string
        }
      }
    }
  }
}